export interface CategoryOption {
  value: string;
  label: string;
}

export const CATEGORIES = [
  { value: 'fashion', label: 'Fashion & Beauty' },
  { value: 'food', label: 'Food & Restaurants' },
  { value: 'tech', label: 'Technology & Gadgets' },
  { value: 'health', label: 'Health, Fitness & Wellness' },
  { value: 'travel', label: 'Travel & Tourism' },
  { value: 'education', label: 'Education & Learning' },
  { value: 'entertainment', label: 'Entertainment & Media' },
  { value: 'business', label: 'Business & Finance' },
  { value: 'lifestyle', label: 'Lifestyle & Personal Development' },
  { value: 'automotive', label: 'Automotive & Transport' },
  { value: 'sports', label: 'Sports & Recreation' },
  { value: 'realestate', label: 'Real Estate & Housing' },
  { value: 'events', label: 'Events & Celebrations' },
  { value: 'gaming', label: 'Gaming & eSports' },
  { value: 'nonprofit', label: 'Non-Profit & Causes' },
  { value: 'politics', label: 'Politics & Government' },
  { value: 'religion', label: 'Religion & Spirituality' },
  { value: 'parenting', label: 'Parenting & Family' },
  { value: 'pets', label: 'Pets & Animals' },
  { value: 'art', label: 'Art, Culture & Photography' },
  { value: 'home', label: 'Home, Garden & DIY' },
  { value: 'science', label: 'Science & Innovation' },
  { value: 'jobs', label: 'Jobs & Career' },
  { value: 'finance', label: 'Investments & Trading' },
  { value: 'insurance', label: 'Insurance & Protection' },
  { value: 'legal', label: 'Legal & Law Services' },
  { value: 'music', label: 'Music & Performances' },
  { value: 'movies', label: 'Movies & Streaming' },
  { value: 'telecom', label: 'Telecom & Internet' },
  { value: 'utilities', label: 'Utilities & Energy' },
  { value: 'crypto', label: 'Crypto & Blockchain' },
  { value: 'environment', label: 'Environment & Sustainability' },
  { value: 'agriculture', label: 'Agriculture & Farming' },
  { value: 'shopping', label: 'Shopping & E-Commerce' },
  { value: 'alcohol', label: 'Alcohol & Beverages' },
  { value: 'beauty', label: 'Cosmetics & Skincare' },
  { value: 'fashionmen', label: 'Men’s Fashion' },
  { value: 'fashionwomen', label: 'Women’s Fashion' },
  { value: 'kids', label: 'Kids & Toys' },
  { value: 'books', label: 'Books & Media' },
  { value: 'luxury', label: 'Luxury & Jewelry' },
  { value: 'arts', label: 'Arts & Crafts' },
  { value: 'software', label: 'Digital Products & Software' },
  { value: 'hardware', label: 'Hardware Products & Electronics' },
  { value: 'productivity', label: 'Productivity & Tools' },
  { value: 'dating', label: 'Dating & Relationships' },
  { value: 'transport', label: 'Transport & Logistics' },
  { value: 'startups', label: 'Startups & Innovation' },
  { value: 'influencers', label: 'Influencers & Personal Brands' },
  { value: 'reviews', label: 'Reviews & Recommendations' },
  { value: 'other', label: 'Other' }
];