interface PhoneCountry {
  name: string;
  iso2: string;
  dialCode: string;
  emoji: string;
}

export const COUNTRY_PHONE_MAP: PhoneCountry[] = [
    { name: 'United States', iso2: 'US', dialCode: '1', emoji: '🇺🇸' },
    { name: 'United Kingdom', iso2: 'GB', dialCode: '44', emoji: '🇬🇧' },
    { name: 'Nigeria', iso2: 'NG', dialCode: '234', emoji: '🇳🇬' },
    { name: 'Canada', iso2: 'CA', dialCode: '1', emoji: '🇨🇦' },
    { name: 'Germany', iso2: 'DE', dialCode: '49', emoji: '🇩🇪' },
    { name: 'France', iso2: 'FR', dialCode: '33', emoji: '🇫🇷' },
    { name: 'India', iso2: 'IN', dialCode: '91', emoji: '🇮🇳' },
    { name: 'China', iso2: 'CN', dialCode: '86', emoji: '🇨🇳' },
    { name: 'Brazil', iso2: 'BR', dialCode: '55', emoji: '🇧🇷' },
    { name: 'South Africa', iso2: 'ZA', dialCode: '27', emoji: '🇿🇦' },
    { name: 'Aruba', iso2: 'AW', dialCode: '297', emoji: '🇦🇼' },
    { name: 'Afghanistan', iso2: 'AF', dialCode: '93', emoji: '🇦🇫' },
    { name: 'Angola', iso2: 'AO', dialCode: '244', emoji: '🇦🇴' },
    { name: 'Anguilla', iso2: 'AI', dialCode: '1-264', emoji: '🇦🇮' },
    { name: 'Åland Islands', iso2: 'AX', dialCode: '358', emoji: '🇦🇽' },
    { name: 'Albania', iso2: 'AL', dialCode: '355', emoji: '🇦🇱' },
    { name: 'Andorra', iso2: 'AD', dialCode: '376', emoji: '🇦🇩' },
    { name: 'United Arab Emirates', iso2: 'AE', dialCode: '971', emoji: '🇦🇪' },
    { name: 'Argentina', iso2: 'AR', dialCode: '54', emoji: '🇦🇷' },
    { name: 'Armenia', iso2: 'AM', dialCode: '374', emoji: '🇦🇲' },
    { name: 'American Samoa', iso2: 'AS', dialCode: '1-684', emoji: '🇦🇸' },
    { name: 'Antarctica', iso2: 'AQ', dialCode: '672', emoji: '🇦🇶' },
    { name: 'French Southern Territories', iso2: 'TF', dialCode: '262', emoji: '🇹🇫' },
    { name: 'Antigua and Barbuda', iso2: 'AG', dialCode: '1-268', emoji: '🇦🇬' },
    { name: 'Australia', iso2: 'AU', dialCode: '61', emoji: '🇦🇺' },
    { name: 'Austria', iso2: 'AT', dialCode: '43', emoji: '🇦🇹' },
    { name: 'Azerbaijan', iso2: 'AZ', dialCode: '994', emoji: '🇦🇿' },
    { name: 'Burundi', iso2: 'BI', dialCode: '257', emoji: '🇧🇮' },
    { name: 'Belgium', iso2: 'BE', dialCode: '32', emoji: '🇧🇪' },
    { name: 'Benin', iso2: 'BJ', dialCode: '229', emoji: '🇧🇯' },
    { name: 'Bonaire, Sint Eustatius and Saba', iso2: 'BQ', dialCode: '599', emoji: '🇧🇶' },
    { name: 'Burkina Faso', iso2: 'BF', dialCode: '226', emoji: '🇧🇫' },
    { name: 'Bangladesh', iso2: 'BD', dialCode: '880', emoji: '🇧🇩' },
    { name: 'Bulgaria', iso2: 'BG', dialCode: '359', emoji: '🇧🇬' },
    { name: 'Bahrain', iso2: 'BH', dialCode: '973', emoji: '🇧🇭' },
    { name: 'Bahamas', iso2: 'BS', dialCode: '1-242', emoji: '🇧🇸' },
    { name: 'Bosnia and Herzegovina', iso2: 'BA', dialCode: '387', emoji: '🇧🇦' },
    { name: 'Saint Barthélemy', iso2: 'BL', dialCode: '590', emoji: '🇧🇱' },
    { name: 'Belarus', iso2: 'BY', dialCode: '375', emoji: '🇧🇾' },
    { name: 'Belize', iso2: 'BZ', dialCode: '501', emoji: '🇧🇿' },
    { name: 'Bermuda', iso2: 'BM', dialCode: '1-441', emoji: '🇧🇲' },
    { name: 'Bolivia, Plurinational State of', iso2: 'BO', dialCode: '591', emoji: '🇧🇴' },
    { name: 'Barbados', iso2: 'BB', dialCode: '1-246', emoji: '🇧🇧' },
    { name: 'Brunei Darussalam', iso2: 'BN', dialCode: '673', emoji: '🇧🇳' },
    { name: 'Bhutan', iso2: 'BT', dialCode: '975', emoji: '🇧🇹' },
    { name: 'Bouvet Island', iso2: 'BV', dialCode: '47', emoji: '🇧🇻' },
    { name: 'Botswana', iso2: 'BW', dialCode: '267', emoji: '🇧🇼' },
    { name: 'Central African Republic', iso2: 'CF', dialCode: '236', emoji: '🇨🇫' },
    { name: 'Cocos (Keeling) Islands', iso2: 'CC', dialCode: '61', emoji: '🇨🇨' },
    { name: 'Switzerland', iso2: 'CH', dialCode: '41', emoji: '🇨🇭' },
    { name: 'Chile', iso2: 'CL', dialCode: '56', emoji: '🇨🇱' },
    { name: 'Côte d\'Ivoire', iso2: 'CI', dialCode: '225', emoji: '🇨🇮' },
    { name: 'Cameroon', iso2: 'CM', dialCode: '237', emoji: '🇨🇲' },
    { name: 'Congo, The Democratic Republic of the', iso2: 'CD', dialCode: '243', emoji: '🇨🇩' },
    { name: 'Congo', iso2: 'CG', dialCode: '242', emoji: '🇨🇬' },
    { name: 'Cook Islands', iso2: 'CK', dialCode: '682', emoji: '🇨🇰' },
    { name: 'Colombia', iso2: 'CO', dialCode: '57', emoji: '🇨🇴' },
    { name: 'Comoros', iso2: 'KM', dialCode: '269', emoji: '🇰🇲' },
    { name: 'Cabo Verde', iso2: 'CV', dialCode: '238', emoji: '🇨🇻' },
    { name: 'Costa Rica', iso2: 'CR', dialCode: '506', emoji: '🇨🇷' },
    { name: 'Cuba', iso2: 'CU', dialCode: '53', emoji: '🇨🇺' },
    { name: 'Curaçao', iso2: 'CW', dialCode: '599', emoji: '🇨🇼' },
    { name: 'Christmas Island', iso2: 'CX', dialCode: '61', emoji: '🇨🇽' },
    { name: 'Cayman Islands', iso2: 'KY', dialCode: '1-345', emoji: '🇰🇾' },
    { name: 'Cyprus', iso2: 'CY', dialCode: '357', emoji: '🇨🇾' },
    { name: 'Czechia', iso2: 'CZ', dialCode: '420', emoji: '🇨🇿' },
    { name: 'Djibouti', iso2: 'DJ', dialCode: '253', emoji: '🇩🇯' },
    { name: 'Dominica', iso2: 'DM', dialCode: '1-767', emoji: '🇩🇲' },
    { name: 'Denmark', iso2: 'DK', dialCode: '45', emoji: '🇩🇰' },
    { name: 'Dominican Republic', iso2: 'DO', dialCode: '1-809', emoji: '🇩🇴' },
    { name: 'Algeria', iso2: 'DZ', dialCode: '213', emoji: '🇩🇿' },
    { name: 'Ecuador', iso2: 'EC', dialCode: '593', emoji: '🇪🇨' },
    { name: 'Egypt', iso2: 'EG', dialCode: '20', emoji: '🇪🇬' },
    { name: 'Eritrea', iso2: 'ER', dialCode: '291', emoji: '🇪🇷' },
    { name: 'Western Sahara', iso2: 'EH', dialCode: '212', emoji: '🇪🇭' },
    { name: 'Spain', iso2: 'ES', dialCode: '34', emoji: '🇪🇸' },
    { name: 'Estonia', iso2: 'EE', dialCode: '372', emoji: '🇪🇪' },
    { name: 'Ethiopia', iso2: 'ET', dialCode: '251', emoji: '🇪🇹' },
    { name: 'Finland', iso2: 'FI', dialCode: '358', emoji: '🇫🇮' },
    { name: 'Fiji', iso2: 'FJ', dialCode: '679', emoji: '🇫🇯' },
    { name: 'Falkland Islands (Malvinas)', iso2: 'FK', dialCode: '500', emoji: '🇫🇰' },
    { name: 'Faroe Islands', iso2: 'FO', dialCode: '298', emoji: '🇫🇴' },
    { name: 'Micronesia, Federated States of', iso2: 'FM', dialCode: '691', emoji: '🇫🇲' },
    { name: 'Gabon', iso2: 'GA', dialCode: '241', emoji: '🇬🇦' },
    { name: 'Georgia', iso2: 'GE', dialCode: '995', emoji: '🇬🇪' },
    { name: 'Guernsey', iso2: 'GG', dialCode: '44', emoji: '🇬🇬' },
    { name: 'Ghana', iso2: 'GH', dialCode: '233', emoji: '🇬🇭' },
    { name: 'Gibraltar', iso2: 'GI', dialCode: '350', emoji: '🇬🇮' },
    { name: 'Guinea', iso2: 'GN', dialCode: '224', emoji: '🇬🇳' },
    { name: 'Guadeloupe', iso2: 'GP', dialCode: '590', emoji: '🇬🇵' },
    { name: 'Gambia', iso2: 'GM', dialCode: '220', emoji: '🇬🇲' },
    { name: 'Guinea-Bissau', iso2: 'GW', dialCode: '245', emoji: '🇬🇼' },
    { name: 'Equatorial Guinea', iso2: 'GQ', dialCode: '240', emoji: '🇬🇶' },
    { name: 'Greece', iso2: 'GR', dialCode: '30', emoji: '🇬🇷' },
    { name: 'Grenada', iso2: 'GD', dialCode: '1-473', emoji: '🇬🇩' },
    { name: 'Greenland', iso2: 'GL', dialCode: '299', emoji: '🇬🇱' },
    { name: 'Guatemala', iso2: 'GT', dialCode: '502', emoji: '🇬🇹' },
    { name: 'French Guiana', iso2: 'GF', dialCode: '594', emoji: '🇬🇫' },
    { name: 'Guam', iso2: 'GU', dialCode: '1-671', emoji: '🇬🇺' },
    { name: 'Guyana', iso2: 'GY', dialCode: '592', emoji: '🇬🇾' },
    { name: 'Hong Kong', iso2: 'HK', dialCode: '852', emoji: '🇭🇰' },
    { name: 'Heard Island and McDonald Islands', iso2: 'HM', dialCode: '672', emoji: '🇭🇲' },
    { name: 'Honduras', iso2: 'HN', dialCode: '504', emoji: '🇭🇳' },
    { name: 'Croatia', iso2: 'HR', dialCode: '385', emoji: '🇭🇷' },
    { name: 'Haiti', iso2: 'HT', dialCode: '509', emoji: '🇭🇹' },
    { name: 'Hungary', iso2: 'HU', dialCode: '36', emoji: '🇭🇺' },
    { name: 'Indonesia', iso2: 'ID', dialCode: '62', emoji: '🇮🇩' },
    { name: 'Isle of Man', iso2: 'IM', dialCode: '44', emoji: '🇮🇲' },
    { name: 'British Indian Ocean Territory', iso2: 'IO', dialCode: '246', emoji: '🇮🇴' },
    { name: 'Ireland', iso2: 'IE', dialCode: '353', emoji: '🇮🇪' },
    { name: 'Iran, Islamic Republic of', iso2: 'IR', dialCode: '98', emoji: '🇮🇷' },
    { name: 'Iraq', iso2: 'IQ', dialCode: '964', emoji: '🇮🇶' },
    { name: 'Iceland', iso2: 'IS', dialCode: '354', emoji: '🇮🇸' },
    { name: 'Israel', iso2: 'IL', dialCode: '972', emoji: '🇮🇱' },
    { name: 'Italy', iso2: 'IT', dialCode: '39', emoji: '🇮🇹' },
    { name: 'Jamaica', iso2: 'JM', dialCode: '1-876', emoji: '🇯🇲' },
    { name: 'Jersey', iso2: 'JE', dialCode: '44', emoji: '🇯🇪' },
    { name: 'Jordan', iso2: 'JO', dialCode: '962', emoji: '🇯🇴' },
    { name: 'Japan', iso2: 'JP', dialCode: '81', emoji: '🇯🇵' },
    { name: 'Kazakhstan', iso2: 'KZ', dialCode: '7', emoji: '🇰🇿' },
    { name: 'Kenya', iso2: 'KE', dialCode: '254', emoji: '🇰🇪' },
    { name: 'Kyrgyzstan', iso2: 'KG', dialCode: '996', emoji: '🇰🇬' },
    { name: 'Cambodia', iso2: 'KH', dialCode: '855', emoji: '🇰🇭' },
    { name: 'Kiribati', iso2: 'KI', dialCode: '686', emoji: '🇰🇮' },
    { name: 'Saint Kitts and Nevis', iso2: 'KN', dialCode: '1-869', emoji: '🇰🇳' },
    { name: 'Korea, Republic of', iso2: 'KR', dialCode: '82', emoji: '🇰🇷' },
    { name: 'Kuwait', iso2: 'KW', dialCode: '965', emoji: '🇰🇼' },
    { name: 'Lao People\'s Democratic Republic', iso2: 'LA', dialCode: '856', emoji: '🇱🇦' },
    { name: 'Lebanon', iso2: 'LB', dialCode: '961', emoji: '🇱🇧' },
    { name: 'Liberia', iso2: 'LR', dialCode: '231', emoji: '🇱🇷' },
    { name: 'Libya', iso2: 'LY', dialCode: '218', emoji: '🇱🇾' },
    { name: 'Saint Lucia', iso2: 'LC', dialCode: '1-758', emoji: '🇱🇨' },
    { name: 'Liechtenstein', iso2: 'LI', dialCode: '423', emoji: '🇱🇮' },
    { name: 'Sri Lanka', iso2: 'LK', dialCode: '94', emoji: '🇱🇰' },
    { name: 'Lesotho', iso2: 'LS', dialCode: '266', emoji: '🇱🇸' },
    { name: 'Lithuania', iso2: 'LT', dialCode: '370', emoji: '🇱🇹' },
    { name: 'Luxembourg', iso2: 'LU', dialCode: '352', emoji: '🇱🇺' },
    { name: 'Latvia', iso2: 'LV', dialCode: '371', emoji: '🇱🇻' },
    { name: 'Macao', iso2: 'MO', dialCode: '853', emoji: '🇲🇴' },
    { name: 'Saint Martin (French part)', iso2: 'MF', dialCode: '590', emoji: '🇲🇫' },
    { name: 'Morocco', iso2: 'MA', dialCode: '212', emoji: '🇲🇦' },
    { name: 'Monaco', iso2: 'MC', dialCode: '377', emoji: '🇲🇨' },
    { name: 'Moldova, Republic of', iso2: 'MD', dialCode: '373', emoji: '🇲🇩' },
    { name: 'Madagascar', iso2: 'MG', dialCode: '261', emoji: '🇲🇬' },
    { name: 'Maldives', iso2: 'MV', dialCode: '960', emoji: '🇲🇻' },
    { name: 'Mexico', iso2: 'MX', dialCode: '52', emoji: '🇲🇽' },
    { name: 'Marshall Islands', iso2: 'MH', dialCode: '692', emoji: '🇲🇭' },
    { name: 'North Macedonia', iso2: 'MK', dialCode: '389', emoji: '🇲🇰' },
    { name: 'Mali', iso2: 'ML', dialCode: '223', emoji: '🇲🇱' },
    { name: 'Malta', iso2: 'MT', dialCode: '356', emoji: '🇲🇹' },
    { name: 'Myanmar', iso2: 'MM', dialCode: '95', emoji: '🇲🇲' },
    { name: 'Montenegro', iso2: 'ME', dialCode: '382', emoji: '🇲🇪' },
    { name: 'Mongolia', iso2: 'MN', dialCode: '976', emoji: '🇲🇳' },
    { name: 'Northern Mariana Islands', iso2: 'MP', dialCode: '1-670', emoji: '🇲🇵' },
    { name: 'Mozambique', iso2: 'MZ', dialCode: '258', emoji: '🇲🇿' },
    { name: 'Mauritania', iso2: 'MR', dialCode: '222', emoji: '🇲🇷' },
    { name: 'Montserrat', iso2: 'MS', dialCode: '1-664', emoji: '🇲🇸' },
    { name: 'Martinique', iso2: 'MQ', dialCode: '596', emoji: '🇲🇶' },
    { name: 'Mauritius', iso2: 'MU', dialCode: '230', emoji: '🇲🇺' },
    { name: 'Malawi', iso2: 'MW', dialCode: '265', emoji: '🇲🇼' },
    { name: 'Malaysia', iso2: 'MY', dialCode: '60', emoji: '🇲🇾' },
    { name: 'Mayotte', iso2: 'YT', dialCode: '262', emoji: '🇾🇹' },
    { name: 'Namibia', iso2: 'NA', dialCode: '264', emoji: '🇳🇦' },
    { name: 'New Caledonia', iso2: 'NC', dialCode: '687', emoji: '🇳🇨' },
    { name: 'Niger', iso2: 'NE', dialCode: '227', emoji: '🇳🇪' },
    { name: 'Norfolk Island', iso2: 'NF', dialCode: '672', emoji: '🇳🇫' },
    { name: 'Nicaragua', iso2: 'NI', dialCode: '505', emoji: '🇳🇮' },
    { name: 'Niue', iso2: 'NU', dialCode: '683', emoji: '🇳🇺' },
    { name: 'Netherlands', iso2: 'NL', dialCode: '31', emoji: '🇳🇱' },
    { name: 'Norway', iso2: 'NO', dialCode: '47', emoji: '🇳🇴' },
    { name: 'Nepal', iso2: 'NP', dialCode: '977', emoji: '🇳🇵' },
    { name: 'Nauru', iso2: 'NR', dialCode: '674', emoji: '🇳🇷' },
    { name: 'New Zealand', iso2: 'NZ', dialCode: '64', emoji: '🇳🇿' },
    { name: 'Oman', iso2: 'OM', dialCode: '968', emoji: '🇴🇲' },
    { name: 'Pakistan', iso2: 'PK', dialCode: '92', emoji: '🇵🇰' },
    { name: 'Panama', iso2: 'PA', dialCode: '507', emoji: '🇵🇦' },
    { name: 'Pitcairn', iso2: 'PN', dialCode: '64', emoji: '🇵🇳' },
    { name: 'Peru', iso2: 'PE', dialCode: '51', emoji: '🇵🇪' },
    { name: 'Philippines', iso2: 'PH', dialCode: '63', emoji: '🇵🇭' },
    { name: 'Palau', iso2: 'PW', dialCode: '680', emoji: '🇵🇼' },
    { name: 'Papua New Guinea', iso2: 'PG', dialCode: '675', emoji: '🇵🇬' },
    { name: 'Poland', iso2: 'PL', dialCode: '48', emoji: '🇵🇱' },
    { name: 'Puerto Rico', iso2: 'PR', dialCode: '1', emoji: '🇵🇷' },
    { name: 'Korea, Democratic People\'s Republic of', iso2: 'KP', dialCode: '850', emoji: '🇰🇵' },
    { name: 'Portugal', iso2: 'PT', dialCode: '351', emoji: '🇵🇹' },
    { name: 'Paraguay', iso2: 'PY', dialCode: '595', emoji: '🇵🇾' },
    { name: 'Palestine, State of', iso2: 'PS', dialCode: '970', emoji: '🇵🇸' },
    { name: 'French Polynesia', iso2: 'PF', dialCode: '689', emoji: '🇵🇫' },
    { name: 'Qatar', iso2: 'QA', dialCode: '974', emoji: '🇶🇦' },
    { name: 'Réunion', iso2: 'RE', dialCode: '262', emoji: '🇷🇪' },
    { name: 'Romania', iso2: 'RO', dialCode: '40', emoji: '🇷🇴' },
    { name: 'Russian Federation', iso2: 'RU', dialCode: '7', emoji: '🇷🇺' },
    { name: 'Rwanda', iso2: 'RW', dialCode: '250', emoji: '🇷🇼' },
    { name: 'Saudi Arabia', iso2: 'SA', dialCode: '966', emoji: '🇸🇦' },
    { name: 'Sudan', iso2: 'SD', dialCode: '249', emoji: '🇸🇩' },
    { name: 'Senegal', iso2: 'SN', dialCode: '221', emoji: '🇸🇳' },
    { name: 'Singapore', iso2: 'SG', dialCode: '65', emoji: '🇸🇬' },
    { name: 'South Georgia and the South Sandwich Islands', iso2: 'GS', dialCode: '500', emoji: '🇬🇸' },
    { name: 'Saint Helena, Ascension and Tristan da Cunha', iso2: 'SH', dialCode: '290', emoji: '🇸🇭' },
    { name: 'Svalbard and Jan Mayen', iso2: 'SJ', dialCode: '47', emoji: '🇸🇯' },
    { name: 'Solomon Islands', iso2: 'SB', dialCode: '677', emoji: '🇸🇧' },
    { name: 'Sierra Leone', iso2: 'SL', dialCode: '232', emoji: '🇸🇱' },
    { name: 'El Salvador', iso2: 'SV', dialCode: '503', emoji: '🇸🇻' },
    { name: 'San Marino', iso2: 'SM', dialCode: '378', emoji: '🇸🇲' },
    { name: 'Somalia', iso2: 'SO', dialCode: '252', emoji: '🇸🇴' },
    { name: 'Saint Pierre and Miquelon', iso2: 'PM', dialCode: '508', emoji: '🇵🇲' },
    { name: 'Serbia', iso2: 'RS', dialCode: '381', emoji: '🇷🇸' },
    { name: 'South Sudan', iso2: 'SS', dialCode: '211', emoji: '🇸🇸' },
    { name: 'Sao Tome and Principe', iso2: 'ST', dialCode: '239', emoji: '🇸🇹' },
    { name: 'Suriname', iso2: 'SR', dialCode: '597', emoji: '🇸🇷' },
    { name: 'Slovakia', iso2: 'SK', dialCode: '421', emoji: '🇸🇰' },
    { name: 'Slovenia', iso2: 'SI', dialCode: '386', emoji: '🇸🇮' },
    { name: 'Sweden', iso2: 'SE', dialCode: '46', emoji: '🇸🇪' },
    { name: 'Eswatini', iso2: 'SZ', dialCode: '268', emoji: '🇸🇿' },
    { name: 'Sint Maarten (Dutch part)', iso2: 'SX', dialCode: '1-721', emoji: '🇸🇽' },
    { name: 'Seychelles', iso2: 'SC', dialCode: '248', emoji: '🇸🇨' },
    { name: 'Syrian Arab Republic', iso2: 'SY', dialCode: '963', emoji: '🇸🇾' },
    { name: 'Turks and Caicos Islands', iso2: 'TC', dialCode: '1-649', emoji: '🇹🇨' },
    { name: 'Chad', iso2: 'TD', dialCode: '235', emoji: '🇹🇩' },
    { name: 'Togo', iso2: 'TG', dialCode: '228', emoji: '🇹🇬' },
    { name: 'Thailand', iso2: 'TH', dialCode: '66', emoji: '🇹🇭' },
    { name: 'Tajikistan', iso2: 'TJ', dialCode: '992', emoji: '🇹🇯' },
    { name: 'Tokelau', iso2: 'TK', dialCode: '690', emoji: '🇹🇰' },
    { name: 'Timor-Leste', iso2: 'TL', dialCode: '670', emoji: '🇹🇱' },
    { name: 'Turkmenistan', iso2: 'TM', dialCode: '993', emoji: '🇹🇲' },
    { name: 'Tunisia', iso2: 'TN', dialCode: '216', emoji: '🇹🇳' },
    { name: 'Tonga', iso2: 'TO', dialCode: '676', emoji: '🇹🇴' },
    { name: 'Turkey', iso2: 'TR', dialCode: '90', emoji: '🇹🇷' },
    { name: 'Trinidad and Tobago', iso2: 'TT', dialCode: '1-868', emoji: '🇹🇹' },
    { name: 'Tuvalu', iso2: 'TV', dialCode: '688', emoji: '🇹🇻' },
    { name: 'Taiwan, Province of China', iso2: 'TW', dialCode: '886', emoji: '🇹🇼' },
    { name: 'Tanzania, United Republic of', iso2: 'TZ', dialCode: '255', emoji: '🇹🇿' },
    { name: 'Ukraine', iso2: 'UA', dialCode: '380', emoji: '🇺🇦' },
    { name: 'Uganda', iso2: 'UG', dialCode: '256', emoji: '🇺🇬' },
    { name: 'Uruguay', iso2: 'UY', dialCode: '598', emoji: '🇺🇾' },
    { name: 'Uzbekistan', iso2: 'UZ', dialCode: '998', emoji: '🇺🇿' },
    { name: 'Holy See', iso2: 'VA', dialCode: '379', emoji: '🇻🇦' },
    { name: 'Saint Vincent and the Grenadines', iso2: 'VC', dialCode: '1-784', emoji: '🇻🇨' },
    { name: 'Venezuela, Bolivarian Republic of', iso2: 'VE', dialCode: '58', emoji: '🇻🇪'},
    { name: 'Virgin Islands, British', iso2: 'VG', dialCode: '1-284', emoji: '🇻🇬' },
    { name: 'Virgin Islands, U.S.', iso2: 'VI', dialCode: '1-340', emoji: '🇻🇮' },
    { name: 'Viet Nam', iso2: 'VN', dialCode: '84', emoji: '🇻🇳' },
    { name: 'Vanuatu', iso2: 'VU', dialCode: '678', emoji: '🇻🇺' },
    { name: 'Wallis and Futuna', iso2: 'WF', dialCode: '681', emoji: '🇼🇫' },
    { name: 'Samoa', iso2: 'WS', dialCode: '685', emoji: '🇼🇸' },
    { name: 'Yemen', iso2: 'YE', dialCode: '967', emoji: '🇾🇪' },
    { name: 'South Africa', iso2: 'ZA', dialCode: '27', emoji: '🇿🇦' },
    { name: 'Zambia', iso2: 'ZM', dialCode: '260', emoji: '🇿🇲' },
    { name: 'Zimbabwe', iso2: 'ZW', dialCode: '263', emoji: '🇿🇼' }
];
